# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec1e87231e766643b2f80227d8470eea4e98190dd09990a1ba478f01b8debf0d1b677773000db49df9f59d2048c097c8cc01d1c72bd9d9c150a7c981e1cb7d2

test:
  secret_key_base: bb45de5059938732300bcd4cdbb638fb0bc344771e5514e7a9f5d9355784f850b8da5ed5d4f05568721491c9be164966009c9210b39033640841de8b94cc74cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
